using Npgsql;

static class CircleSchema
{
    public static async Task MigrateAsync(NpgsqlConnection connection)
    {
        await using var transaction = await connection.BeginTransactionAsync();
        await using var command = new NpgsqlCommand("""
            create table if not exists system_circles (
              id text primary key,
              "ownerUserId" bigint not null unique references user_accounts(id) on delete cascade,
              name text not null check (length(trim(name)) between 1 and 100),
              comment text not null check (length(comment) <= 1000),
              play_time_start integer not null check (play_time_start between -1 and 29),
              play_time_end integer not null check (play_time_end between -1 and 29),
              entry_type integer not null check (entry_type between 0 and 2),
              member_type integer not null check (member_type between 0 and 2),
              company_master_id bigint,
              character_base_master_id bigint,
              banner bytea,
              is_publish_ranking boolean not null default false,
              created_at timestamptz not null default now()
            );
            create table if not exists user_circle_memberships (
              "userId" bigint primary key references user_accounts(id) on delete cascade,
              circle_id text not null references system_circles(id) on delete cascade,
              authority integer not null check (authority between 1 and 3),
              joined_at timestamptz not null default now()
            );
            create index if not exists user_circle_memberships_circle_id_idx on user_circle_memberships(circle_id);
            alter table system_circles add column if not exists is_publish_ranking boolean not null default false;
            alter table user_circle_memberships add column if not exists stamina_last_received_at timestamptz;
            alter table system_circles add column if not exists display_id integer
              generated by default as identity (start with 10000001 minvalue 10000001 maxvalue 99999999);
            create unique index if not exists system_circles_display_id_idx on system_circles(display_id);
            alter table system_circles add column if not exists previous_display_id integer;
            create unique index if not exists system_circles_previous_display_id_idx on system_circles(previous_display_id);
            create or replace function system_random_circle_display_id() returns integer language plpgsql volatile as $function$
            declare candidate integer;
            begin
              for attempt in 1..32 loop
                candidate := floor(random() * 90000000)::integer + 10000000;
                if not exists(select 1 from system_circles where display_id = candidate or previous_display_id = candidate) then
                  return candidate;
                end if;
              end loop;
              raise exception '社团随机编号分配失败';
            end;
            $function$;
            do $migration$
            declare circle record;
            begin
              if exists(select 1 from information_schema.columns where table_schema = current_schema()
                and table_name = 'system_circles' and column_name = 'display_id' and is_identity = 'YES') then
                alter table system_circles alter column display_id drop identity;
                update system_circles set previous_display_id = display_id;
                for circle in select id from system_circles order by id loop
                  update system_circles set display_id = system_random_circle_display_id() where id = circle.id;
                end loop;
              end if;
            end;
            $migration$;
            alter table system_circles alter column display_id set default system_random_circle_display_id();
            """, connection, transaction);
        await command.ExecuteNonQueryAsync();
        await transaction.CommitAsync();
    }
}
